### ISSUE TITLE
Recruitment test 

### ISSUE THREAD

**Issue by Aglae16** [Ipuch/Recruitement_test#1]
Après avoir pas mal modifier le script du test de recrutement, je dois encore afficher 'tau' et 'q' dans un même graphique de la manière la plus claire possible. Actuellement, j'ai réussi à obtenir les différents graphiques mais je dois maintenant les rassembler. Pourriez-vous m'aider s'il vous plaît? 
Merci d'avance!

**Comment by Ipuch** [comment]
Vous pouvez utiliser matplotlib par exemple?

**Comment by Aglae16** [comment]
Oui, c'est ce que j'ai fait, mais quand je run le programme aucune courbe supplémentaire n'apparait. J'ai du faire une erreur dans le choix des abscisses et des ordonnées peut-être?
A ce stade, j'ai réussi à obtenir en fonction du temps les courbes suivantes : q_Seg1_TransY, Q_Seg2_RotX, qdot_0, qdot_1, tau_0, tau_1, Minimize control et continuity.
